### ISSUE TITLE
Vugu v1.0 ToDo List

### ISSUE THREAD

**Issue by owenwaller** [vugu/vugu#260]
# Background

With reference to Issue #246

This issue serves as the ToDo list for Vugu v1.0.

*Please note* To goal of the v1.0 release is to get `vugu` stable, updated to work with the current Go tool chain, to make `vugu` easier to use from a developer perspective - including both simpler tooling and better documentation.

We don't want to take major new features in this release. We can focus on these after the v1.0 release.

If there is something that you think is missing for the v1.0 release can you please give us your feedback in issue #246.
If we keep everything in Issue #246 that the complete discussion thread is available. We'll update this issue based on that discussion.

Please consider this list a **draft**. @bradleypeabody  and I have been discussing what we want to change via Slack. This list represents our current thoughts. 

# ToDo

- [ ] Build with go v1.21.4+. We intend to only support the two versions of Go that the Go team support going forward. Which `Tinygo` versions we support is still to be discussed.
- [ ] Upgrade Vugu dependencies.
- [ ] Upgrade TinyGo to v0.30 (the current version).
- [ ] Lint the `vugu` source code with [golangci-lint](https://golangci-lint.run/). *Note:* we need to add a config for for this into the repo. 
- [ ] Document how to build a `vugu` application using only the standard Go tool chain.
- [ ] Document how to deploy a `vugu` application using `nginx` as a web server.
- [ ] Correct the auto-generated coment to match the standard Go form.
- [ ] Add `_gen` to generated file names.
- [ ] Extend/Update the examples in the [vugu-examples](https://github.com/vugu-examples/).
- [ ] Move to a [Taskfile](https://taskfile.dev/) based build process for the `vugu-examples`. And recommend this approach for all `vugu` projects.
- [ ] Move to a [Taskfile](https://taskfile.dev/) for `vugu` itself. This simplifies building and testing `vugu` locally.
- [ ] Create a new `vgutil` tool to help simplify the `Taskfile`. This is largely used to generate a new `index.htnml` file from a Go template.
- [ ] Depreciate the `vgrun` tool. The new `Taskfile` approach supersedes it.
- [ ] Depreciate the `devserver.go` development server. The `Taskfile` approach uses an `nginx` in a container to serve the `vugu` application.
- [ ] Depreciate the current [Building and Distribution](https://www.vugu.org/doc/build-and-dist) advice. The new documentation that shows how to deploy to an `nginx` server and the `Taskfile` approach both make this redundant.
- [ ] Document (and show in the examples) how things like CSS processors or webpack builders can be called from the `Taskfile` rather then make then part of `vugu` itself.
- [ ] Depreciate the "FullHTML" mode. The new `Taskfile` approach and the new `vgutil` command that generates the `index.html` file form a Go template make this redundant (as far as I can tell!).
- [ ] Depreciate the `simplehttp` package? *Note:* We don't need this for production any more, but we may need it for testing. So this may move the `simplehttp` package to a test support package.
- [ ] Possibly spit the test suite into three. One suite each that uses the standard Go compiler, a `tinygo` compiler installed locally, a `tinygo` compiler in a docker container. This would simplify testing of `vugu`.
- [ ] Add code (test) coverage metrics?. See things like the [Go coverage Tree Heatmap](https://github.com/nikolaydubina/go-cover-treemap)
- [ ] Work out what happens to the `vgforms` package. At the minute we plan to build the examples and use those to see if this package needs to be updated (if at all). 
- [ ] Fix any outstanding bugs :smile: 

# Examples

At the minute we are thinking of reworking the vugu examples as a tutorial series. The topics are likely to be:

* A simple example that shows you how to build and deploy. This is likely to be variation on the existing [simple](https://github.com/vugu-examples/simple) but reworked to show you how to use the new `Taskfile` approach.
* A Set of examples that show: 
  1. How to manipulate the DOM
  2. How to create new components 
  3. How to wire components
  4. How routing works
  5. How to organise source code to split the Go source files (which contain the logic) from the `.vugu` files which contains the layout, and the CSS files that contain the presentation.
  6. How to manage long running tasks e.g. HTTP fetch calls from `vugu`.
  7. Maybe show how JS scripts can be integrated. This is likely to be *limited* to scripts that do **not** manipulate the DOM. Using an existing JS charting library would be a good example of what we might support.
* How to integrate with other tooling e.g CSS minimisers or packers, by extending the `Taskfile`. Possibly based on Tailwind (or Bootstrap CSS or both?) 
* A more complete and fulling production ready example, possibly based the [taco-store](https://github.com/vugu-examples/taco-store) example.
* An example that uses `tinygo` to demonstrate the different ways `tinygo` can be run to create the final Web Assembly.

# Building and Deploying with Go and Nginx

Just so folks are aware of this. There is a [new Wiki page](https://github.com/vugu/vugu/wiki/Building-With-Go-and-Deploying-with-nginx) that documents how to build `vugu` applications using only the standard Go tool chain and then deploying the resulting Web Assembly binary into a `nginx` running in a container. This is still a draft document, so feedback from the community would be welcomed.
